[package]
name = "encryption-app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl-sys = "0.9"
openssl = "0.10"
rocket = "0.5.0-rc.2"
base64 = "0.21.0"
